Updated Jenkins file

diff --git a/jenkins-ci-cd-pipeline/app/JenkinsFile b/jenkins-ci-cd-pipeline/app/JenkinsFile
--- a/jenkins-ci-cd-pipeline/app/JenkinsFile
+++ b/jenkins-ci-cd-pipeline/app/JenkinsFile
@@ -8,25 +8,34 @@ pipeline {
         SSH_CRED = "ec2-ssh-key"
     }
     stages {
+        stage('Cleanup') {
+            steps {
+               deleteDir()   // deletes everything in workspace before cloning
+              }
+        }
         stage('Checkout') {
            steps {
-             checkout scm
+              sh "git clone 'https://github.com/lucifer045/Devops-portfolio.git'"
             }
         }
         stage("Build Docker Image"){
             steps{
-                sh "docker build -t ${IMAGE_NAME}:${TAG} ."
+                sh "docker build -t ${IMAGE_NAME}:${TAG} -f Devops-portfolio/jenkins-ci-cd-pipeline/app/Dockerfile Devops-portfolio/jenkins-ci-cd-pipeline/app/"
             }
         }
-        stage('Trivy Scan') {
-           steps {
-              // install trivy in the agent or use container; here assuming trivy is installed
-              sh "trivy image --exit-code 1 --severity HIGH,CRITICAL ${IMAGE_NAME}:${TAG} || true"
-           }
+       stage('Trivy Scan') {
+          steps {
+             sh """
+                 docker run --rm \
+                 -v /var/run/docker.sock:/var/run/docker.sock \
+                 -v \$HOME/Library/Caches:/root/.cache/ \
+                 aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL ${IMAGE_NAME}:${TAG} || true
+            """
+            }
         }
         stage('Login and Push'){
            steps{
-               withCredentials([usernamePassword(credentialsId: "${DOCKER_CRED}", usernameVAR: "DockerUser", usernamePASS: "DockerPass")]){
+               withCredentials([usernamePassword(credentialsId: "${DOCKER_CRED}", usernameVariable: "DockerUser", passwordVariable: "DockerPass")]){
                    sh "echo \"$DockerPass\" | docker login -u \"$DockerUser\" --password-stdin "
                    sh "docker push ${IMAGE_NAME}:${TAG}"
                }
@@ -36,23 +45,29 @@ pipeline {
           steps {
             sshagent (credentials: ["${SSH_CRED}"]) {
                 sh """
-                 ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-149-254-204.us-east-2.compute.amazonaws.com'
-                 docker pull ${IMAGE_NAME}:${TAG} &&
-                 docker stop app || true &&
-                 docker rm app || true &&
-                 docker run -d --name app -p 80:5000 ${IMAGE_NAME}:${TAG}
+                 ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-219-200-168.us-east-2.compute.amazonaws.com '
+                 sudo docker pull ${IMAGE_NAME}:${TAG} &&
+                 sudo docker stop app || true &&
+                 sudo docker rm app || true &&
+                 sudo docker run -d --name app -p 80:5000 ${IMAGE_NAME}:${TAG} &&
+                 sudo docker ps -a
                 '
                 """
               }
          }
       }
+    }  
     post {
        always {
-        echo "Pipeline finished"
-       }
+         echo "Pipeline finished"
+         }
        failure {
+<<<<<<< HEAD
         mail to: 'yoyed38662@lovleo.com', subject: "Build failed: ${currentBuild.fullDisplayName}", body: "${env.BUILD_URL}"
        }
+=======
+         echo "Pipleine failed"
+         }
+>>>>>>> 9ab29b2 (Updated Jenkins file)
     }
-  }
 }
